kind: pipeline
name: ci

steps:
  - name: build
    image: docker
    commands:
    - docker build -t vehicle-compliance-checker-frontend:latest --build-arg COMPLIANCE_CHECKER_API_URL=http://localhost:8000 .
    environment:
      GOOGLE_ANALYTICS_ID:
        from_secret: GOOGLE_ANALYTICS_ID
      SECRET_KEY_BASE:
        from_secret: SECRET_KEY_BASE
      COMPLIANCE_CHECKER_API_URL:
        from_secret: COMPLIANCE_CHECKER_API_URL
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: ruby_env_file
        path: /var/drone/.env

  - name: test
    image: vehicle-compliance-checker-frontend:latest
    pull: if-not-exists
    commands:
    - ls
    - ls public
    - ls public/packs-test/
    - cat public/packs-test/manifest.json
    - rake 
    volumes:
    - name: bundle
      path: /usr/local/bundle
    - name: docker_sock
      path: /var/run/docker.sock
    settings:
      build_args_from_env:
        - SECRET_KEY_BASE
    environment:
      GOOGLE_ANALYTICS_ID:
        from_secret: GOOGLE_ANALYTICS_ID
      SECRET_KEY_BASE:
        from_secret: SECRET_KEY_BASE
      COMPLIANCE_CHECKER_API_URL:
        from_secret: COMPLIANCE_CHECKER_API_URL

volumes:
- name: bundle
  temp: {}
- name: docker_sock
  host:
    path: /var/run/docker.sock
- name: ruby_env_file
  host:
    path: /var/drone/.env

trigger:
  event:
  - pull_request
