kind: pipeline
name: ci

steps:
  - name: test
    image: timbru31/ruby-node
    commands:
    - gem install bundler --version 2.0.2
    - export BUNDLER_VERSION=2.0.2
    - bundle install
    - yarn install --check-files
    - bundle exec rails webpacker:compile
    - rake
    volumes:
    - name: bundle
      path: /usr/local/bundle
    settings:
      build_args_from_env:
        - SECRET_KEY_BASE
    environment:
      GOOGLE_ANALYTICS_ID:
        from_secret: GOOGLE_ANALYTICS_ID
      SECRET_KEY_BASE:
        from_secret: SECRET_KEY_BASE
      COMPLIANCE_CHECKER_API_URL:
        from_secret: COMPLIANCE_CHECKER_API_URL

volumes:
- name: bundle
  temp: {}

trigger:
  event:
  - pull_request
