kind: pipeline
name: ci

# Build and test combined to protect from asset loss
steps:
  - name: build-test
    image: docker
    commands:
    - docker build -t vehicle-compliance-checker-frontend:latest --build-arg secret_key_base=secret .
    - docker run --rm -e COMPLIANCE_CHECKER_API_URL=http://localhost vehicle-compliance-checker-frontend rspec -f d
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  - name: publish-to-ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo: 018330602464.dkr.ecr.eu-west-2.amazonaws.com/caz-global-ecr
      registry: 018330602464.dkr.ecr.eu-west-2.amazonaws.com
      region: eu-west-2
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - pull_request
