kind: pipeline
name: ci

# Build and test combined to protect from asset loss
steps:
              
  - name: build-test
    image: docker
    commands:
    - docker system prune -f
    - docker build -t vehicle-compliance-checker-frontend:latest --build-arg secret_key_base=secret .
    - docker run --rm -e COMPLIANCE_CHECKER_API_URL=http://localhost vehicle-compliance-checker-frontend rspec -f d
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  - name: publish-image-to-ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo: 018330602464.dkr.ecr.eu-west-2.amazonaws.com/vccs
      registry: 018330602464.dkr.ecr.eu-west-2.amazonaws.com
      region: eu-west-2
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}

  - name: deploy
    image: hashicorp/terraform:0.12.3
    commands:
      - git clone https://github.com/InformedSolutions/JAQU-CAZ-IAC.git
      - cd JAQU-CAZ-IAC/terraform/projects/vccs/environments/dev
      - terraform init
      - terraform apply -auto-approve
    environment:
      TF_VAR_build_number: ${DRONE_BUILD_NUMBER}
      TF_VAR_compliance_checker: https://jaqu-caz.herokuapp.com
      TF_VAR_access_key: 
        from_secret: aws_access_key_id      
      TF_VAR_secret_key:
        from_secret: aws_secret_access_key        

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - pull_request
