kind: pipeline
name: ci

# Build and test combined to protect from asset loss
steps:
  - name: build-test
    image: docker
    commands:
    - docker build -t vehicle-compliance-checker-frontend:latest --build-arg secret_key_base=secret .
    - docker run --rm -e COMPLIANCE_CHECKER_API_URL=http://localhost vehicle-compliance-checker-frontend rspec -f d
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - pull_request
