kind: pipeline
name: ci

steps:
  - name: build
    image: docker
    commands:
    - docker build -t vehicle-compliance-checker-frontend:latest --build-arg SECRET_KEY_BASE=123 --build-arg GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} --build-arg COMPLIANCE_CHECKER_API_URL=http://localhost:8000 .
    - 
    settings:
      build_args_from_env:
        - SECRET_KEY_BASE
    environment:
      GOOGLE_ANALYTICS_ID:
        from_secret: GOOGLE_ANALYTICS_ID
      SECRET_KEY_BASE:
        from_secret: SECRET_KEY_BASE
      COMPLIANCE_CHECKER_API_URL:
        from_secret: COMPLIANCE_CHECKER_API_URL
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: ruby_env_file
        path: /var/drone/.env

  - name: test
    image: vehicle-compliance-checker-frontend:latest
    pull: if-not-exists
    commands:
    # - gem install bundler --version 2.0.2
    # - export BUNDLER_VERSION=2.0.2
    # - bundle install
    # - yarn install --check-files
    # - bundle exec rails webpacker:compile
    - rake /home/app
    volumes:
    - name: bundle
      path: /usr/local/bundle
    - name: docker_sock
      path: /var/run/docker.sock
    settings:
      build_args_from_env:
        - SECRET_KEY_BASE
    environment:
      GOOGLE_ANALYTICS_ID:
        from_secret: GOOGLE_ANALYTICS_ID
      SECRET_KEY_BASE:
        from_secret: SECRET_KEY_BASE
      COMPLIANCE_CHECKER_API_URL:
        from_secret: COMPLIANCE_CHECKER_API_URL

volumes:
- name: bundle
  temp: {}
- name: docker_sock
  host:
    path: /var/run/docker.sock
- name: ruby_env_file
  host:
    path: /var/drone/.env

trigger:
  event:
  - pull_request
