require:
  - rubocop-rails
  - rubocop-rspec

inherit_from: ./lib/rubocop/blacklist.yml

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable

Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#']

Metrics/ClassLength:
  Max: 110

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Style/MixinUsage:
  Exclude:
    - 'features/step_definitions/*.rb'

# rubocop-rspec gem excludes
RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 9

RSpec/DescribeClass:
  Exclude:
    - 'spec/api_wrappers/compliance_checker_api/*.rb'
