kind: pipeline
name: ci

clone:
  depth: 1

steps:
  - name: test
    image: ruby
    commands:
    - gem install bundler --version 2.0.2 --force
    - bundle install
    - rake
    volumes:
    - name: bundle
      path: /usr/local/bundle
    build_args:
      - secret_key_base=86da409854bc321174383cb143ce1f25bbce493846d69bf120e9489b3766616b8a0c7a2fe1242efd4180010efd4cd73ba9d3cb430974edbbe734359ff99e9733

volumes:
- name: bundle
  temp: {}

trigger:
  event:
  - pull_request
